$vm_count = 3
$hostname = "vagrant-vm-"
$domain = "local"
$ip = "192.168.71"
$host_port = 808
$ssl_host_port = 844
$port = 80
$ssl_port = 443

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box = "starboard/ubuntu-arm64-20.04.5"
    config.vm.box_version = "20221120.20.40.0"
    config.vm.box_download_insecure = true
    config.vm.provider "vmware_desktop" do |v|
        v.ssh_info_public = true
        v.gui = true
        v.linked_clone = false
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"
        v.vmx["memsize"] = "2048"
        v.vmx["numvcpus"] = "1"
        v.vmx["ethernet0.pcislotnumber"] = "160"
    end

    (1..$vm_count).each do |i|
        config.vm.define "#{$hostname}#{i}" do |vagrant|
            vagrant.vm.network "forwarded_port", guest: "#{$port}", host: "#{$host_port}#{0+i}"
            vagrant.vm.network "forwarded_port", guest: "#{$ssl_port}", host: "#{$ssl_host_port}#{2+i}"
            vagrant.vm.hostname = "#{$hostname}#{i}.#{$domain}"
            vagrant.vm.network "private_network", ip: "#{$ip}.#{99+i}", hostname: true
        end
    end
end
