Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box = "starboard/ubuntu-arm64-20.04.5"
    config.vm.box_version = "20221120.20.40.0"
    config.vm.box_download_insecure = true
    config.vm.provider "vmware_desktop" do |v|
        #TODO  apt update
        v.ssh_info_public = true
        v.gui = true
        v.linked_clone = false
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"
        v.vmx["memsize"] = "2048"
        v.vmx["numvcpus"] = "1"
        v.vmx["ethernet0.pcislotnumber"] = "160"

    end

    config.vm.define "vagrant-vm-1" do |vagrant1|
        vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
        vagrant1.vm.network "forwarded_port", guest: 443, host: 8443
        vagrant1.vm.hostname = "vagrant-vm-1.local"
        vagrant1.vm.network "private_network", ip: "192.168.71.100", hostname: true
    end

    config.vm.define "vagrant-vm-2" do |vagrant2|
        vagrant2.vm.network "forwarded_port", guest: 80, host: 8081
        vagrant2.vm.network "forwarded_port", guest: 443, host: 8444
        vagrant2.vm.hostname = "vagrant-vm-2.local"
        vagrant2.vm.network "private_network", ip: "192.168.71.101", hostname: true
    end

    config.vm.define "vagrant-vm-3" do |vagrant3|
        vagrant3.vm.network "forwarded_port", guest: 80, host: 8082
        vagrant3.vm.network "forwarded_port", guest: 443, host: 8445
        vagrant3.vm.hostname = "vagrant-vm-3.local"
        vagrant3.vm.network "private_network", ip: "192.168.71.102", hostname: true
    end

end
